VirtualBox COM Server 5.1.26 r117224 win.amd64 (Jul 27 2017 12:32:13) release log
00:00:00.343754 main     Log opened 2017-12-23T14:54:10.404007100Z
00:00:00.343754 main     Build Type: release
00:00:00.343754 main     OS Product: Windows 8.1
00:00:00.343754 main     OS Release: 6.3.9600
00:00:00.343754 main     OS Service Pack: 
00:00:10.706615 main     DMI Product Name: Inspiron 5537
00:00:10.722212 main     DMI Product Version: A07
00:00:10.722212 main     Host RAM: 8072MB (7.8GB) total, 6428MB (6.2GB) available
00:00:10.722212 main     Executable: C:\Program Files\Oracle\VirtualBox\VBoxSVC.exe
00:00:10.722212 main     Process ID: 3292
00:00:10.722212 main     Package type: WINDOWS_64BITS_GENERIC
00:00:11.347201          VirtualBox: object creation starts
00:00:11.347201          Home directory: 'C:\Users\Ulhas\.VirtualBox'
00:00:11.347201          Installed Drivers:
00:00:11.378452            C:\WINDOWS\system32\DRIVERS\VBoxNetLwf.sys (Version: 5.1.26.17224)
00:00:11.409706            C:\WINDOWS\system32\DRIVERS\VBoxUSBMon.sys (Version: 5.1.26.17224)
00:00:11.769074            C:\WINDOWS\system32\DRIVERS\VBoxDrv.sys (Version: 5.1.26.17224)
00:00:11.847200            C:\WINDOWS\system32\DRIVERS\VBoxNetAdp6.sys (Version: 5.1.26.17224)
00:00:11.862826          Loading settings file "C:\Users\Ulhas\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
00:00:11.974619          Getting USB descriptor failed with error 31
00:00:11.974619          USB: Unknown USB device detected (idVendor: 0x0c45, idProduct: 0x64ad)
00:00:11.974619          USB: Unknown USB device detected (idVendor: 0x8087, idProduct: 0x07dc)
00:00:12.021533          HostDnsMonitorProxy::notify
00:00:12.255915          VD: VDInit finished
00:00:12.255915          Loading settings file "C:\Users\Ulhas\VirtualBox VMs\Ansible_Control_Machine\Ansible_Control_Machine.vbox" with version "1.16-windows"
00:00:12.255915          Loading settings file "C:\Users\Ulhas\VirtualBox VMs\Ansible_node_1\Ansible_node_1.vbox" with version "1.16-windows"
00:00:12.255915          Loading settings file "C:\Users\Ulhas\VirtualBox VMs\Ansible_Node_2\Ansible_Node_2.vbox" with version "1.16-windows"
00:00:12.255915          VirtualBox: object created
00:00:34.870977 USBPROXY Getting USB descriptor failed with error 31
00:00:55.399398 USBPROXY Getting USB descriptor failed with error 31
00:00:56.248219          ERROR [COM]: aRC=VBOX_E_OBJECT_NOT_FOUND (0x80bb0001) aIID={edba9d10-45d8-b440-1712-46ac0c9bc4c5} aComponent={ExtPackManagerWrap} aText={No extension pack by the name 'Oracle VM VirtualBox Extension Pack' was found}, preserve=false aResultDetail=0
00:00:56.367014          ERROR [COM]: aRC=VBOX_E_IPRT_ERROR (0x80bb0005) aIID={b2547866-a0a1-4391-8b86-6952d82efaa0} aComponent={SessionMachine} aText={Saved screenshot data is not available (VERR_NOT_SUPPORTED)}, preserve=false aResultDetail=0
00:01:14.014694          ERROR [COM]: aRC=VBOX_E_OBJECT_NOT_FOUND (0x80bb0001) aIID={edba9d10-45d8-b440-1712-46ac0c9bc4c5} aComponent={ExtPackManagerWrap} aText={No extension pack by the name 'Oracle VM VirtualBox Extension Pack' was found}, preserve=false aResultDetail=0
00:01:14.125325          ERROR [COM]: aRC=VBOX_E_IPRT_ERROR (0x80bb0005) aIID={b2547866-a0a1-4391-8b86-6952d82efaa0} aComponent={SessionMachine} aText={Saved screenshot data is not available (VERR_NOT_SUPPORTED)}, preserve=false aResultDetail=0
00:01:24.306064          ERROR [COM]: aRC=VBOX_E_OBJECT_NOT_FOUND (0x80bb0001) aIID={edba9d10-45d8-b440-1712-46ac0c9bc4c5} aComponent={ExtPackManagerWrap} aText={No extension pack by the name 'Oracle VM VirtualBox Extension Pack' was found}, preserve=false aResultDetail=0
00:01:24.384270          ERROR [COM]: aRC=VBOX_E_IPRT_ERROR (0x80bb0005) aIID={b2547866-a0a1-4391-8b86-6952d82efaa0} aComponent={SessionMachine} aText={Saved screenshot data is not available (VERR_NOT_SUPPORTED)}, preserve=false aResultDetail=0
00:02:51.242676 USBPROXY Getting USB descriptor failed with error 31
00:02:54.798938 dns-monitor HostDnsMonitor: old information
00:02:54.798938 dns-monitor   no server entries
00:02:54.799916 dns-monitor   no domain set
00:02:54.799916 dns-monitor   no search string entries
00:02:54.799916 dns-monitor HostDnsMonitor: new information
00:02:54.799916 dns-monitor   server 1: 192.168.43.1
00:02:54.799916 dns-monitor   no domain set
00:02:54.799916 dns-monitor   no search string entries
00:02:54.799916 dns-monitor HostDnsMonitorProxy::notify
00:18:08.388364 USBPROXY Getting USB descriptor failed with error 31
00:18:08.391307 USBPROXY Getting USB descriptor failed with error 31
00:18:54.807448 USBPROXY Getting USB descriptor failed with error 31
00:23:03.564436 USBPROXY Getting USB descriptor failed with error 31
00:27:56.986721 USBPROXY Getting USB descriptor failed with error 31
02:34:23.200977 MainPower Host suspending: Paused 3 VMs
02:56:35.352832 dns-monitor HostDnsMonitor: old information
02:56:35.352832 dns-monitor   server 1: 192.168.43.1
02:56:35.352832 dns-monitor   no domain set
02:56:35.352832 dns-monitor   no search string entries
02:56:35.352832 dns-monitor HostDnsMonitor: new information
02:56:35.352832 dns-monitor   no server entries
02:56:35.352832 dns-monitor   no domain set
02:56:35.352832 dns-monitor   no search string entries
02:56:35.352832 dns-monitor HostDnsMonitorProxy::notify
02:56:38.155938 MainPower Host resumed: Resumed 3 VMs
02:57:37.008936 main     VirtualBox: object deletion starts
02:57:37.040146 main     ERROR [COM]: aRC=VBOX_E_OBJECT_IN_USE (0x80bb000c) aIID={4afe423b-43e0-e9d0-82e8-ceb307940dda} aComponent={MediumWrap} aText={Medium 'C:\Users\Ulhas\VirtualBox VMs\Ansible_Control_Machine\Ansible_Control_Machine.vdi' cannot be closed because it is still attached to 1 virtual machines}, preserve=false aResultDetail=0
02:57:37.087047 main     ERROR [COM]: aRC=VBOX_E_OBJECT_IN_USE (0x80bb000c) aIID={4afe423b-43e0-e9d0-82e8-ceb307940dda} aComponent={MediumWrap} aText={Medium 'C:\Users\Ulhas\VirtualBox VMs\Ansible_node_1\Ansible_node_1.vdi' cannot be closed because it is still attached to 1 virtual machines}, preserve=false aResultDetail=0
02:57:37.087047 main     ERROR [COM]: aRC=VBOX_E_OBJECT_IN_USE (0x80bb000c) aIID={4afe423b-43e0-e9d0-82e8-ceb307940dda} aComponent={MediumWrap} aText={Medium 'C:\Users\Ulhas\VirtualBox VMs\Ansible_Node_2\Ansible_Node_2.vdi' cannot be closed because it is still attached to 1 virtual machines}, preserve=false aResultDetail=0
02:57:37.477691 Watcher  ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={0169423f-46b4-cde9-91af-1e9d5b6cd945} aComponent={VirtualBoxWrap} aText={The object is not ready}, preserve=false aResultDetail=0
02:57:37.540192 main     VirtualBox: object deleted
